// Data pariwisata Pulau Madura — 60 destinasi wisata dari 4 kabupaten.

export const destinations = [
  // ==================== BANGKALAN (15 Items) ====================
  // Alam (3 Items)
  {
    id: 1,
    name: "Bukit Jaddih",
    location: "Bangkalan",
    category: "Alam",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1616422961567-0cce3ff826fa?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Bukit kapur putih raksasa eksotis dengan kolam pemandian Gua Pote.",
    description: "Bukit Jaddih merupakan kawasan penambangan batu kapur putih aktif seluas lebih dari 500 hektar yang kini menjadi destinasi wisata paling ikonik di Bangkalan. Pemandangan bukit kapur raksasa berpadu dengan kolam air berwarna hijau kebiruan (Gua Pote) memberikan nuansa eksotis yang menyerupai bentang alam luar negeri.",
    hours: "07:00 - 17:00 WIB",
    price: "Rp 10.000",
    facilities: ["Area Parkir Luas", "Warung Kuliner", "Spot Foto", "Toilet", "Penyewaan Perahu"],
    address: "Desa Jaddih, Kecamatan Socah, Bangkalan",
    lat: -7.0861,
    lng: 112.7415,
    nearbyCulinary: ["Bebek Sinjay", "Tajin Sobih"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  {
    id: 2,
    name: "Bukit Kapur Arosbaya",
    location: "Bangkalan",
    category: "Alam",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Bukit kapur merah eksotis bekas pahatan tambang berbentuk lorong-lorong gua.",
    description: "Bukit Kapur Arosbaya menawarkan keunikan tebing kapur berwarna cokelat kemerahan yang terbentuk akibat pahatan manual para penambang liar. Bentukan pahatan menghasilkan koridor-koridor mirip kastil kuno dan gua berlorong gelap namun sangat fotogenik dengan dedaunan paku liar merambat di sela dinding batu.",
    hours: "08:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Area Parkir", "Warung Makanan", "Spot Foto Seni", "Pemandu Lokal"],
    address: "Desa Buduran, Kecamatan Arosbaya, Bangkalan",
    lat: -7.0083,
    lng: 112.7843,
    nearbyCulinary: ["Nasi Serpang", "Tajin Sobih"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  {
    id: 3,
    name: "Mata Air Sumber Pocong",
    location: "Bangkalan",
    category: "Alam",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1432406186170-ee5fd378846e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pemandian alam tersembunyi dengan air yang sangat jernih dan pepohonan rindang.",
    description: "Sumber Pocong adalah mata air alami tersembunyi yang memiliki kualitas kejernihan air yang luar biasa. Dinamakan unik karena dahulu konon dekat dengan kuburan mistis, kini tempat ini dikelola menjadi kolam renang alami yang sejuk dengan dasar bebatuan alam, dikelilingi rindangnya pohon kelapa dan bambu.",
    hours: "06:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Kamar Mandi Bilas", "Penyewaan Ban", "Warung Kopi", "Mushola"],
    address: "Desa Pokopen, Kecamatan Trigah, Bangkalan",
    lat: -7.0478,
    lng: 112.7592,
    nearbyCulinary: ["Sate Madura", "Tajin Sobih"],
    nearbyMsmes: ["Toko Mainan Tradisional"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  // Pantai (3 Items)
  {
    id: 4,
    name: "Pantai Rongkang",
    location: "Bangkalan",
    category: "Pantai",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai berbatu dengan tebing eksotis dekat Jembatan Suramadu.",
    description: "Pantai Rongkang menawarkan pemandangan eksotis pesisir berbatu dengan jajaran pohon rindang serta hamparan batuan karang yang menahan abrasi. Pada malam hari, pantai ini menyuguhkan panorama kelap-kelip lampu Jembatan Suramadu yang membentang gagah membelah Selat Madura.",
    hours: "24 Jam",
    price: "Rp 5.000",
    facilities: ["Gazebo", "Warung Kopi", "Area Parkir Motor", "Spot Foto Suramadu"],
    address: "Desa Kwanyar Barat, Kecamatan Kwanyar, Bangkalan",
    lat: -7.1604,
    lng: 112.8093,
    nearbyCulinary: ["Soto Madura", "Bebek Sinjay"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Lomba Perahu Tradisional"]
  },
  {
    id: 5,
    name: "Pantai Siring Kemuning",
    location: "Bangkalan",
    category: "Pantai",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai pasir kuning keemasan yang tenang di pesisir utara Bangkalan.",
    description: "Pantai Siring Kemuning menyajikan pasir pantai berwarna kuning keemasan yang unik dan deburan ombak tenang khas pesisir laut utara Jawa. Pohon kelapa berjajar rapi di tepian pantai, menjadikannya lokasi ideal untuk piknik keluarga dan berburu pemandangan matahari terbenam yang damai.",
    hours: "06:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Mushola", "Toilet", "Warung Es Kelapa Muda", "Taman Bermain Sederhana"],
    address: "Desa Mecajah, Kecamatan Tanjung Bumi, Bangkalan",
    lat: -6.9021,
    lng: 112.9115,
    nearbyCulinary: ["Sate Madura", "Tajin Sobih"],
    nearbyMsmes: ["Sentra Batik Tanjung Bumi"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 6,
    name: "Pantai Pasir Putih Tlangoh",
    location: "Bangkalan",
    category: "Pantai",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Destinasi wisata pantai pasir putih ramah keluarga dengan ayunan tepi laut.",
    description: "Pantai Tlangoh adalah objek wisata bahari baru yang berkembang pesat berkat keindahan pasir putih bersih membentang luas. Pantai ini dilengkapi ayunan kayu di tepi laut, dekorasi spot selfie modern, serta penyewaan ATV pantai untuk menelusuri pesisir laut utara Bangkalan.",
    hours: "07:00 - 18:00 WIB",
    price: "Rp 10.000",
    facilities: ["Kamar Mandi Bilas", "Penyewaan ATV", "Warung Makanan Ringan", "Gazebo Teduh"],
    address: "Desa Tlangoh, Kecamatan Tanjung Bumi, Bangkalan",
    lat: -6.8895,
    lng: 112.8698,
    nearbyCulinary: ["Sate Madura", "Bebek Sinjay"],
    nearbyMsmes: ["Sentra Batik Tanjung Bumi"],
    relatedEvents: ["Festival Bahari Selat Madura"]
  },
  // Budaya (3 Items)
  {
    id: 7,
    name: "Sentra Batik Tanjung Bumi",
    location: "Bangkalan",
    category: "Budaya",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1601391942646-621e25e98218?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Desa perajin penghasil Batik Gentongan tradisional bernilai seni tinggi.",
    description: "Tanjung Bumi merupakan sentra kerajinan batik tulis tertua di Madura. Ciri khas utamanya adalah teknik Batik Gentongan yang membutuhkan perendaman kain dalam gentong tanah liat selama berbulan-bulan untuk mendapatkan pewarnaan alami eksklusif yang sangat awet.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Galeri Batik", "Toko Souvenir", "Edukasi Membatik", "Parkiran Luas"],
    address: "Desa Tanjung Bumi, Kecamatan Tanjung Bumi, Bangkalan",
    lat: -6.9055,
    lng: 112.9228,
    nearbyCulinary: ["Tajin Sobih", "Sate Madura"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Madura Batik Festival"]
  },
  {
    id: 8,
    name: "Karapan Sapi Bangkalan",
    location: "Bangkalan",
    category: "Budaya",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Stadion latihan dan pelestarian pacuan karapan sapi khas Madura.",
    description: "Karapan sapi adalah olahraga tradisional paling bergengsi di Madura. Di arena ini, sepasang sapi pilihan yang telah dilatih berbulan-bulan berlari kencang menarik keleles dengan joki cilik berpengalaman di atasnya. Suara saronen yang riuh dan sorak-sorai penonton menciptakan atmosfer yang tak terlupakan.",
    hours: "08:00 - 15:00 WIB (Hanya saat latihan/lomba)",
    price: "Rp 15.000",
    facilities: ["Stadion Terbuka", "Area Kandang Sapi", "Warung Makanan", "Toilet"],
    address: "Stadion Skep, Bancaran, Kecamatan Bangkalan, Bangkalan",
    lat: -7.0189,
    lng: 112.7621,
    nearbyCulinary: ["Bebek Sinjay", "Soto Madura"],
    nearbyMsmes: ["Toko Mainan Tradisional"],
    relatedEvents: ["Karapan Sapi (Piala Presiden)", "Pertunjukan Karapan Sapi Sonok"]
  },
  {
    id: 9,
    name: "Museum Cakraningrat",
    location: "Bangkalan",
    category: "Budaya",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Museum penyimpanan benda pusaka bersejarah peninggalan adipati Bangkalan.",
    description: "Museum Cakraningrat menyimpan ratusan koleksi pusaka bersejarah, mulai dari keris kuno, tombak, kereta kencana adipati, gamelan kuno, koin uang kolonial, hingga replika pakaian adat pengantin agung bangsawan Bangkalan masa silam.",
    hours: "08:00 - 14:00 WIB",
    price: "Rp 5.000",
    facilities: ["Pemandu Museum", "Ruang Edukasi", "Kamar Mandi", "Toko Souvenir"],
    address: "Jl. Soekarno-Hatta No. 35, Kecamatan Bangkalan, Bangkalan",
    lat: -7.0393,
    lng: 112.7481,
    nearbyCulinary: ["Bebek Sinjay", "Tajin Sobih"],
    nearbyMsmes: ["Toko Mainan Tradisional"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  // Religi (3 Items)
  {
    id: 10,
    name: "Makam Syaikhona Kholil",
    location: "Bangkalan",
    category: "Religi",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam ulama kharismatik guru para kiai besar pendiri Nahdlatul Ulama.",
    description: "Makam Syaikhona Kholil di Desa Martajesah merupakan salah satu tempat ziarah paling ramai dikunjungi di Jawa Timur. Syaikhona Kholil adalah ulama besar Nusantara abad ke-19 yang menjadi guru dari para pendiri organisasi Islam terbesar di Indonesia. Kompleks makam dilengkapi masjid berarsitektur Timur Tengah yang indah.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Masjid Agung", "Kamar Mandi Umum", "Pasar Souvenir Religi", "Parkir Bus Luas"],
    address: "Desa Martajesah, Kecamatan Bangkalan, Bangkalan",
    lat: -7.0419,
    lng: 112.7231,
    nearbyCulinary: ["Bebek Sinjay", "Soto Madura"],
    nearbyMsmes: ["Toko Mainan Tradisional"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 11,
    name: "Pasarean Bujuk Cendana",
    location: "Bangkalan",
    category: "Religi",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam penyebar syiar Islam awal di pesisir Kwanyar Bangkalan.",
    description: "Makam suci kuno Bujuk Cendana atau Syekh Zainal Abidin merupakan leluhur spiritual yang membawa ajaran Islam mula-mula ke pesisir selatan Bangkalan. Terletak di perbukitan rindang kwanyar yang sejuk dan sakral.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Pendopo Peziarah", "Mushola", "Tempat Wudhu", "Warung Makanan"],
    address: "Desa Ketetang, Kecamatan Kwanyar, Bangkalan",
    lat: -7.1593,
    lng: 112.8288,
    nearbyCulinary: ["Soto Madura", "Bebek Sinjay"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Festival Budaya Karapan Sapi"]
  },
  {
    id: 12,
    name: "Asta Bujuk Lattee",
    location: "Bangkalan",
    category: "Religi",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam keramat wali pembawa keberkahan tani di dataran tinggi Bangkalan.",
    description: "Asta Bujuk Lattee dikeramatkan warga sebagai situs pemakaman wali penyebar dakwah tani. Dipercaya mendatangkan berkat ketenteraman pertanian pedesaan. Tempat ini ramai diziarahi santri lokal di malam Jumat Manis.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Mushola", "Area Parkir Motor", "Toilet", "Pondok Santai"],
    address: "Desa Geger, Kecamatan Geger, Bangkalan",
    lat: -7.0029,
    lng: 112.8538,
    nearbyCulinary: ["Sate Madura", "Nasi Serpang"],
    nearbyMsmes: ["Toko Mainan Tradisional"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  // Sejarah (3 Items)
  {
    id: 13,
    name: "Mercusuar Sembilangan",
    location: "Bangkalan",
    category: "Sejarah",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Mercusuar bersejarah peninggalan kolonial Belanda setinggi 78 meter.",
    description: "Mercusuar Sembilangan dibangun pada 1879 oleh pemerintah Kerajaan Belanda untuk memandu kapal-kapal yang melintas di Selat Madura. Menara besi bundar setinggi 78 meter ini masih berfungsi hingga hari ini dan menjadi salah satu bangunan bersejarah tertua yang masih utuh di Madura. Dari puncak menara, panorama Selat Madura terhampar indah.",
    hours: "08:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Warung Kopi", "Spot Foto Sunset", "Toilet Sederhana", "Area Parkir"],
    address: "Desa Sembilangan, Kecamatan Bangkalan, Bangkalan",
    lat: -7.0600,
    lng: 112.6745,
    nearbyCulinary: ["Soto Madura", "Tajin Sobih"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Festival Bahari Selat Madura"]
  },
  {
    id: 14,
    name: "Pasarean Plakaran",
    location: "Bangkalan",
    category: "Sejarah",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Situs pemakaman Ki Lesap dan Raja-Raja awal dinasti Cakraningrat.",
    description: "Situs Pasarean Plakaran menyimpan kisah perjuangan rakyat Madura melalui makam Ki Lesap dan para leluhur dinasti Cakraningrat. Ki Lesap dikenal sebagai tokoh yang berani menentang monopoli kekuasaan asing di tanah Madura, menjadikannya pahlawan di hati masyarakat setempat.",
    hours: "08:00 - 16:00 WIB",
    price: "Sukarela",
    facilities: ["Papan Sejarah", "Pendopo Makam", "Area Parkir"],
    address: "Desa Plakaran, Kecamatan Arosbaya, Bangkalan",
    lat: -7.0105,
    lng: 112.7826,
    nearbyCulinary: ["Nasi Serpang", "Tajin Sobih"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 15,
    name: "Benteng Pertahanan VOC Kalimo'ok",
    location: "Bangkalan",
    category: "Sejarah",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Reruntuhan sisa benteng pertahanan militer VOC Belanda abad ke-18.",
    description: "Situs reruntuhan pos pertahanan militer Vereenigde Oostindische Compagnie (VOC) yang dahulu dibangun untuk menjaga jalur perdagangan laut di Selat Madura utara. Kini menyisakan fondasi batu bata merah tebal kuno eksotis.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Spot Foto Sejarah", "Area Parkir Motor"],
    address: "Desa Kalimo'ok, Socah, Bangkalan",
    lat: -7.0843,
    lng: 112.7391,
    nearbyCulinary: ["Bebek Sinjay", "Tajin Sobih"],
    nearbyMsmes: ["Batik Tresna Art"],
    relatedEvents: ["Festival Bahari Selat Madura"]
  },

  // ==================== SAMPANG (15 Items) ====================
  // Alam (3 Items)
  {
    id: 16,
    name: "Air Terjun Toroan",
    location: "Sampang",
    category: "Alam",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1432406186170-ee5fd378846e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Air terjun unik yang mengalir langsung jatuh ke bibir pantai laut lepas.",
    description: "Air Terjun Toroan adalah fenomena alam langka di mana aliran air terjun tawar setinggi 20 meter jatuh langsung menghujam ke bibir pantai berpasir dan bermuara di laut lepas pantai utara. Pemandangan tebing karang dan gemuruh air terjun sangat memukau.",
    hours: "07:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Spot Foto Selfie", "Warung Makanan", "Mushola", "Toilet", "Pondok Istirahat"],
    address: "Desa Ketapang Daya, Kecamatan Ketapang, Sampang",
    lat: -6.8927,
    lng: 113.3124,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 17,
    name: "Gua Lebar Sampang",
    location: "Sampang",
    category: "Alam",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Gua kapur alam raksasa bekas galian kapur di tengah wilayah perkotaan.",
    description: "Gua Lebar terbentuk secara menakjubkan berupa tebing kapur raksasa membentuk cekungan raksasa mirip gua terbuka di tengah kota Sampang. Tebing kapur yang berwarna putih kekuningan dihiasi tanaman liar eksotis nan hijau asri.",
    hours: "07:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Taman Bersantai", "Gazebo Karang", "Spot Foto Tebing", "Toilet"],
    address: "Kelurahan Dalpenang, Kecamatan Sampang, Sampang",
    lat: -7.2078,
    lng: 113.2488,
    nearbyCulinary: ["Bebek Songkem", "Campor Lorjuk"],
    nearbyMsmes: ["Kerajinan Kuningan"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  {
    id: 18,
    name: "Bukit Bujel Geger Sampang",
    location: "Sampang",
    category: "Alam",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1501441858156-e505efa0cbaf?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Bukit kapur tinggi dengan panorama alam hijau persawahan Sampang.",
    description: "Bukit Bujel Geger menyuguhkan pesona dataran tinggi berbalut hutan jati dan persawahan hijau. Wisatawan dapat mendaki gardu pandang kayu untuk melihat sejauh mata memandang panorama pedesaan Sampang dari ketinggian.",
    hours: "08:00 - 17:30 WIB",
    price: "Rp 5.000",
    facilities: ["Gardu Pandang", "Area Berkemah", "Warung Makanan", "Parkir Motor"],
    address: "Desa Geger, Kecamatan Kedungdung, Sampang",
    lat: -7.0998,
    lng: 113.2944,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  // Pantai (3 Items)
  {
    id: 19,
    name: "Pantai Camplong",
    location: "Sampang",
    category: "Pantai",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai landai ramah anak dengan taman teduh pesisir Selat Madura.",
    description: "Pantai Camplong adalah destinasi bahari terpopuler di Sampang. Terletak di tepi jalan raya nasional, pantai ini memiliki hamparan pasir landai luas dengan pohon kelapa rindang, taman bermain, dan ombak bersahabat.",
    hours: "06:00 - 18:00 WIB",
    price: "Rp 15.000",
    facilities: ["Hotel & Resort", "Seafood Resto", "Taman Bermain Anak", "Gazebo", "Perahu Wisata"],
    address: "Kelurahan Camplong, Kecamatan Camplong, Sampang",
    lat: -7.2183,
    lng: 113.3168,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Lomba Perahu Tradisional", "Madura Culinary Festival"]
  },
  {
    id: 20,
    name: "Pantai Hutan Kera Nepa",
    location: "Sampang",
    category: "Pantai",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai pasir putih asri yang dikelilingi hutan lindung ribuan kera liar.",
    description: "Pantai Nepa memiliki kombinasi unik berupa hamparan pasir putih pantai utara dengan kawasan hutan mangrove lindung seluas puluhan hektar yang dihuni ribuan kera liar ekor panjang ramah bersahabat.",
    hours: "06:00 - 17:30 WIB",
    price: "Rp 5.000",
    facilities: ["Kamar Mandi Bilas", "Pemandu Hutan", "Toko Pakan Kera", "Warung Kelapa"],
    address: "Desa Batioh, Kecamatan Banyuates, Sampang",
    lat: -6.8874,
    lng: 113.2055,
    nearbyCulinary: ["Campor Lorjuk", "Bebek Songkem"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 21,
    name: "Pantai Jodoh",
    location: "Sampang",
    category: "Pantai",
    rating: 4.1,
    image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai romantis berhias saung kayu terapung di pesisir utara Sampang.",
    description: "Pantai Jodoh menghadirkan pesona pantai santai dengan deretan saung-saung istirahat bambu yang menjorok ke arah bibir pantai. Populer dikalangan pemuda karena spot foto bertema cinta dan kuliner hidangan laut segar.",
    hours: "07:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Saung Terapung", "Warung Ikan Bakar", "Toilet", "Mushola"],
    address: "Desa Bira Timur, Kecamatan Sokobanah, Sampang",
    lat: -6.8842,
    lng: 113.3638,
    nearbyCulinary: ["Sate Madura", "Bebek Songkem"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  // Budaya (3 Items)
  {
    id: 22,
    name: "Sanggar Seni Tari Malate Senggapan",
    location: "Sampang",
    category: "Budaya",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pusat seni pelestarian tari adat Muang Sangkal dan pecut Sampang.",
    description: "Tempat berkumpulnya pegiat seni tradisional tari daerah dan pencak silat khas Sampang. Wisatawan dapat menyaksikan pertunjukan latihan tari tradisional kolosal anak-anak muda secara berkala.",
    hours: "09:00 - 16:00 WIB (Hanya Sabtu-Minggu)",
    price: "Donasi",
    facilities: ["Pendopo Sanggar", "Studio Latihan", "Toko Souvenir Aksesoris Tari"],
    address: "Kelurahan Rongtengah, Kecamatan Sampang, Sampang",
    lat: -7.2130,
    lng: 113.2462,
    nearbyCulinary: ["Bebek Songkem", "Campor Lorjuk"],
    nearbyMsmes: ["Kerajinan Kuningan"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 23,
    name: "Kerajinan Kuningan Karang Penang",
    location: "Sampang",
    category: "Budaya",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Sentra kerajinan pembuatan gong dan seruling gamelan saronen kuno.",
    description: "Karang Penang terkenal sebagai satu-satunya pusat penempaan kuningan tradisional di Sampang yang memproduksi alat musik tradisional Madura seperti trompet saronen, gong, kenong, dan saron kuningan kuno berkualitas tinggi.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Bengkel Kerja Tempa", "Galeri Alat Musik", "Pemandu Pengrajin"],
    address: "Desa Karang Penang Oloh, Kecamatan Karang Penang, Sampang",
    lat: -7.1278,
    lng: 113.3389,
    nearbyCulinary: ["Sate Madura", "Bebek Songkem"],
    nearbyMsmes: ["Kerajinan Kuningan"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 24,
    name: "Sentra Batik Tulis Sampang",
    location: "Sampang",
    category: "Budaya",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1601391942646-621e25e98218?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pusat batik tulis khas Sampang bercorak flora warna-warni cerah.",
    description: "Sentra kerajinan batik tulis Sampang terkenal dengan penggunaan warna-warna mencolok seperti merah terang, kuning, dan hijau botol yang melambangkan keberanian warga pesisir pesisir selatan Sampang.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Galeri Batik", "Area Praktek Membatik", "Toilet", "Warung Teh"],
    address: "Desa Banyumas, Kecamatan Sampang, Sampang",
    lat: -7.1882,
    lng: 113.2198,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Batik Festival"]
  },
  // Religi (3 Items)
  {
    id: 25,
    name: "Makam Rato Ebu Madegan",
    location: "Sampang",
    category: "Religi",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Kompleks makam adipati wanita Madura sakral dengan ukiran nisan klasik.",
    description: "Makam Rato Ebu adalah tempat persemayaman Ratu Ibu, ibunda dari Cakraningrat II, penguasa legendaris Sampang. Kompleks makam dihiasi ukiran nisan batu bermotif perpaduan Hindu-Islam dari abad ke-16. Setiap musim ziarah, ribuan peziarah datang dari berbagai penjuru Jawa dan Madura untuk berdoa di sini.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Pendopo Doa", "Kamar Mandi Umum", "Mushola", "Parkiran Luas"],
    address: "Desa Polagan, Kecamatan Sampang, Sampang",
    lat: -7.2271,
    lng: 113.2588,
    nearbyCulinary: ["Bebek Songkem", "Campor Lorjuk"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 26,
    name: "Asta Bujuk Nepa",
    location: "Sampang",
    category: "Religi",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam pemuka agama Islam kuno di dalam hutan kera keramat Nepa.",
    description: "Situs makam sakral penyebar agama Islam awal di kawasan pesisir utara Sampang, Raden Segoro. Makam ini dikelilingi hutan lindung dengan ribuan monyet ekor panjang yang dipercaya menjaga keamanan situs suci ini.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Mushola Hutan", "Petunjuk Ziarah", "Penjual Pisang"],
    address: "Desa Batioh, Kecamatan Banyuates, Sampang",
    lat: -6.8877,
    lng: 113.2062,
    nearbyCulinary: ["Sate Madura", "Bebek Songkem"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 27,
    name: "Makam Syekh Samsudin",
    location: "Sampang",
    category: "Religi",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam penyebar dakwah syiar Islam di tepian pantai selatan Sampang.",
    description: "Kompleks pemakaman sunyi Syekh Samsudin di tepi laut selatan Sampang yang damai. Menjadi rujukan ziarah tahlil akbar bagi para nelayan pesisir ketika perayaan syawal usai melaut.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Mushola Pantai", "Area Parkir Motor", "Kamar Mandi Sederhana"],
    address: "Desa Camplong, Kecamatan Camplong, Sampang",
    lat: -7.2408,
    lng: 113.3188,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Lomba Perahu Tradisional"]
  },
  // Sejarah (3 Items)
  {
    id: 28,
    name: "Situs Sumur Daksirin",
    location: "Sampang",
    category: "Sejarah",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Sumur batu kuno peninggalan era peralihan kerajaan Hindu-Islam.",
    description: "Situs purbakala berupa sumur dinding batu alam tebal peninggalan abad pertengahan Madura. Dipercaya dahulu berfungsi sebagai sumber air minum utama bagi laskar Kerajaan Madegan Sampang.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Papan Penjelasan", "Tempat Duduk Batu"],
    address: "Desa Polagan, Kecamatan Sampang, Sampang",
    lat: -7.2284,
    lng: 113.2582,
    nearbyCulinary: ["Bebek Songkem", "Campor Lorjuk"],
    nearbyMsmes: ["Kerajinan Kuningan"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 29,
    name: "Makam Pangeran Santrimulyo",
    location: "Sampang",
    category: "Sejarah",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam bangsawan Adipati pertama Sampang utusan Kesultanan Demak.",
    description: "Makam bersejarah Pangeran Santrimulyo, tokoh bangsawan terhormat yang diutus Kesultanan Demak pasca keruntuhan Majapahit untuk memerintah dan menjaga kedamaian wilayah Sampang.",
    hours: "08:00 - 16:30 WIB",
    price: "Sukarela",
    facilities: ["Pendopo Makam", "Area Parkir", "Informasi Silsilah Raja"],
    address: "Kelurahan Karang Dalam, Kecamatan Sampang, Sampang",
    lat: -7.2181,
    lng: 113.2396,
    nearbyCulinary: ["Bebek Songkem", "Soto Madura"],
    nearbyMsmes: ["Sentra Batik Sampang"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 30,
    name: "Prasasti Candi Madegan",
    location: "Sampang",
    category: "Sejarah",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Sisa reruntuhan batu prasasti berukir tulisan Jawa Kuno pra-Islam.",
    description: "Situs purbakala berupa batu-batu prasasti kuno bertuliskan huruf Kawi abad ke-14 yang melegitimasi keberadaan wilayah perdikan Madegan pada era kekuasaan Majapahit di Madura.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Pagar Pelindung", "Informasi Arkeolog"],
    address: "Desa Madegan, Kelurahan Polagan, Sampang",
    lat: -7.2278,
    lng: 113.2594,
    nearbyCulinary: ["Bebek Songkem", "Campor Lorjuk"],
    nearbyMsmes: ["Kerajinan Kuningan"],
    relatedEvents: ["Madura Cultural Festival"]
  },

  // ==================== PAMEKASAN (15 Items) ====================
  // Alam (3 Items)
  {
    id: 31,
    name: "Api Tak Kunjung Padam",
    location: "Pamekasan",
    category: "Alam",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1501441858156-e505efa0cbaf?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Fenomena unik api abadi alami dari dalam tanah yang melegenda.",
    description: "Api Tak Kunjung Padam adalah keajaiban alam yang telah dikenal warga Madura sejak ratusan tahun lalu. Dari celah tanah berkapur di Desa Larangan Tokol, gas bumi secara alami menyembur dan terbakar membentuk nyala api abadi yang tidak pernah padam meski disiram air. Tempat ini menjadi ikon wisata alam Pamekasan yang wajib dikunjungi.",
    hours: "24 Jam",
    price: "Rp 5.000",
    facilities: ["Toko Oleh-oleh", "Warung Sate", "Tempat Duduk Santai", "Toilet", "Mushola"],
    address: "Desa Larangan Tokol, Kecamatan Tlanakan, Pamekasan",
    lat: -7.2050,
    lng: 113.4588,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },
  {
    id: 32,
    name: "Rawa Mangrove Kadur",
    location: "Pamekasan",
    category: "Alam",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Hutan bakau lindung lebat dengan jembatan tracking kayu yang estetik.",
    description: "Rawa Mangrove Kadur dikelola secara ekowisata dengan menghadirkan jembatan kayu terapung membelah rimbunnya hutan bakau pesisir utara. Tempat yang asri dan sejuk untuk berfoto dan melihat burung rawa migran.",
    hours: "08:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Tracking Board", "Menara Pandang", "Kantin Mangrove", "Toilet"],
    address: "Desa Kadur, Kecamatan Kadur, Pamekasan",
    lat: -7.0492,
    lng: 113.5581,
    nearbyCulinary: ["Sate Madura", "Bebek Songkem"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },
  {
    id: 33,
    name: "Bukit Waru Pamekasan",
    location: "Pamekasan",
    category: "Alam",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1432406186170-ee5fd378846e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Tebing batu karst menjulang tinggi dengan lanskap perbukitan hijau.",
    description: "Bukit Waru menghadirkan tebing-tebing batu kapur vertikal kokoh yang populer bagi komunitas pemanjat tebing lokal. Di puncaknya terdapat pohon-pohon waru rindang dan gua alam karst tempat perlindungan burung.",
    hours: "07:00 - 17:30 WIB",
    price: "Rp 5.000",
    facilities: ["Spot Panjat Tebing", "Warung Makanan", "Parkiran Sederhana"],
    address: "Desa Waru Barat, Kecamatan Waru, Pamekasan",
    lat: -6.9138,
    lng: 113.5197,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  // Pantai (3 Items)
  {
    id: 34,
    name: "Pantai Talang Siring",
    location: "Pamekasan",
    category: "Pantai",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai dengan jembatan kayu membelah rerimbunan hutan mangrove pantai.",
    description: "Pantai Talang Siring memadukan keindahan pantai pesisir berpasir dengan hutan bakau alami yang dikembangkan dengan jembatan kayu serta saung santai bertingkat di tepi Selat Madura.",
    hours: "06:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Mushola", "Jembatan Mangrove", "Taman Bermain", "Kios Makanan"],
    address: "Desa Montok, Kecamatan Larangan, Pamekasan",
    lat: -7.1384,
    lng: 113.5894,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Lorjuk Olahan Camilan"],
    relatedEvents: ["Festival Budaya Karapan Sapi"]
  },
  {
    id: 35,
    name: "Pantai Jumiang Pamekasan",
    location: "Pamekasan",
    category: "Pantai",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai tebing karang tinggi dengan pemandangan lepas Selat Madura.",
    description: "Pantai Jumiang terletak di atas tebing karang tinggi di pesisir selatan Pamekasan. Menyuguhkan panorama deburan ombak Selat Madura menghantam batuan karang dan sunset merah keemasan nan romantis.",
    hours: "06:00 - 18:30 WIB",
    price: "Rp 5.000",
    facilities: ["Spot Foto Tebing", "Gazebo Istirahat", "Toilet", "Warung Rujak"],
    address: "Desa Tanjung, Kecamatan Pademawu, Pamekasan",
    lat: -7.2122,
    lng: 113.5038,
    nearbyCulinary: ["Campor Lorjuk", "Sate Madura"],
    nearbyMsmes: ["Lorjuk Olahan Camilan"],
    relatedEvents: ["Festival Budaya Karapan Sapi"]
  },
  {
    id: 36,
    name: "Pantai Batu Kerbuy",
    location: "Pamekasan",
    category: "Pantai",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai berbatu karang raksasa datar menyerupai kerbau mandi.",
    description: "Batu Kerbuy terkenal akan hamparan batuan karang laut datar berwarna abu-abu gelap kehitaman yang membentang di pinggir pantai utara, menyerupai kawanan kerbau (kerbuy) yang sedang berendam di air laut.",
    hours: "06:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Warung Kopi Pantai", "Area Parkir Mobil", "Spot Sunset"],
    address: "Desa Batu Kerbuy, Kecamatan Pasean, Pamekasan",
    lat: -6.8818,
    lng: 113.5381,
    nearbyCulinary: ["Sate Madura", "Bebek Songkem"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  // Budaya (3 Items)
  {
    id: 37,
    name: "Sentra Batik Klampar",
    location: "Pamekasan",
    category: "Budaya",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1601391942646-621e25e98218?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Kampung perajin batik tulis terbesar dengan pewarnaan berani Pamekasan.",
    description: "Klampar adalah jantung industri batik tulis Pamekasan. Hampir seluruh warganya berprofesi sebagai pembatik, menghasilkan kain-kain cantik dengan motif khas daerah seperti motif Podhek (burung kepodang) bergradasi warna merah, oranye, dan kuning cerah. Berkunjung ke sini adalah pengalaman melihat langsung proses membatik dari tangan para ahlinya.",
    hours: "08:00 - 18:00 WIB",
    price: "Gratis",
    facilities: ["Showroom Batik", "Edukasi Canting & Lilin", "Parkir Mobil", "Toilet"],
    address: "Desa Klampar, Kecamatan Proppo, Pamekasan",
    lat: -7.1388,
    lng: 113.4298,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Madura Batik Festival"]
  },
  {
    id: 38,
    name: "Sanggar Seni Saronen Pamekasan",
    location: "Pamekasan",
    category: "Budaya",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pusat kesenian musik tiup tradisional saronen pengiring karapan sapi.",
    description: "Pusat pelestarian dan sanggar latihan musik Saronen. Terdiri dari pemain tiup selompret khas Madura dikombinasikan dengan kendang, gong, dan kenong kuningan kuno yang menghasilkan irama dinamis membakar semangat.",
    hours: "09:00 - 17:00 WIB (Hanya Sabtu-Minggu)",
    price: "Donasi",
    facilities: ["Pendopo Gamelan", "Toko CD Musik Tradisional", "Penyewaan Alat Musik"],
    address: "Jl. Ronggosukowati No. 12, Pamekasan",
    lat: -7.1511,
    lng: 113.4832,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Karapan Sapi (Piala Presiden)"]
  },
  {
    id: 39,
    name: "Kampung Pembuat Pecut Karapan",
    location: "Pamekasan",
    category: "Budaya",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "UMKM khusus pembuat pecut cambuk karapan sapi hias khas Pamekasan.",
    description: "Sentra kerajinan pembuatan pecut (cambuk) khusus karapan sapi yang dibuat dari lilitan benang nilon, kulit sapi, dan hiasan manik-manik rumbai emas. Pecut ini digunakan joki karapan sekaligus benda seni cinderamata bernilai jual tinggi.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Galeri Kerajinan Pecut", "Edukasi Menganyam"],
    address: "Desa Klampar, Kecamatan Proppo, Pamekasan",
    lat: -7.1397,
    lng: 113.4304,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Karapan Sapi (Piala Presiden)"]
  },
  // Religi (3 Items)
  {
    id: 40,
    name: "Pasarean Wali Batu Ampar",
    location: "Pamekasan",
    category: "Religi",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Kompleks pemakaman wali songo versi Madura yang penuh suasana mistis-karomah.",
    description: "Pasarean Wali Batu Ampar adalah kompleks makam keramat yang menjadi tujuan ziarah dari seluruh penjuru Nusantara. Di sini bersemayam Syekh Abdul Manan beserta keturunannya yang dikenal luas sebagai Wali Batu Ampar. Suasana yang tenang, alunan dzikir, dan bau dupa kayu cendana menciptakan kekhusyukan spiritual yang mendalam.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Masjid Peziarah", "Pendopo Dzikir", "Kamar Mandi/Wudhu", "Pasar Cinderamata", "Parkiran Luas"],
    address: "Desa Batu Ampar, Kecamatan Proppo, Pamekasan",
    lat: -7.1098,
    lng: 113.3878,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 41,
    name: "Masjid Agung Asy-Syuhada Pamekasan",
    location: "Pamekasan",
    category: "Religi",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Masjid bersejarah pusat syiar Islam megah di alun-alun kota.",
    description: "Masjid Agung Asy-Syuhada berdiri megah menghadap alun-alun kota Pamekasan. Dibangun sejak abad ke-16, masjid ini memiliki arsitektur perpaduan kubah hijau khas Timur Tengah dengan pilar-pilar kayu jati tua yang kokoh. Masjid ini menjadi pusat kegiatan keagamaan dan kemasyarakatan warga Pamekasan hingga hari ini.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Ruang Shalat Utama Ac", "Perpustakaan Islam", "Halaman Asri", "Tempat Wudhu Modern"],
    address: "Jl. Masegit No. 1, Kecamatan Pamekasan, Pamekasan",
    lat: -7.1584,
    lng: 113.4782,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },
  {
    id: 42,
    name: "Vihara Avalokitesvara",
    location: "Pamekasan",
    category: "Religi",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Vihara tertua Madura dengan perpaduan arsitektur klenteng ikonik.",
    description: "Vihara Avalokitesvara di Galis, Pamekasan merupakan simbol indahnya toleransi beragama. Di dalam vihara ini terdapat peninggalan patung kaisar Tiongkok, arsitektur klenteng merah menyala, serta altar suci yang berdampingan harmonis dengan pura Hindu.",
    hours: "07:00 - 18:00 WIB",
    price: "Donasi",
    facilities: ["Altar Ibadah", "Taman Bunga Lampion", "Spot Foto Seni", "Toilet"],
    address: "Desa Polagan, Kecamatan Galis, Pamekasan",
    lat: -7.1692,
    lng: 113.5588,
    nearbyCulinary: ["Campor Lorjuk", "Sate Madura"],
    nearbyMsmes: ["Lorjuk Olahan Camilan"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },
  // Sejarah (3 Items)
  {
    id: 43,
    name: "Monumen Arek Lancor Pamekasan",
    location: "Pamekasan",
    category: "Sejarah",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Monumen bambu runcing di alun-alun kota simbol perjuangan rakyat.",
    description: "Monumen Arek Lancor berbentuk tiga bambu runcing yang menjulang tinggi di pusat alun-alun kota Pamekasan. Monumen ini didirikan untuk mengenang semangat perjuangan para pejuang Madura yang dengan gagah berani mempertahankan tanah airnya dari penjajahan. Kini menjadi ruang publik yang ramai dikunjungi warga setiap sore dan malam hari.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Taman Kota Rindang", "Kios Makanan Ringan", "Spot Foto Selfie"],
    address: "Pusat Alun-Alun Kota Pamekasan, Pamekasan",
    lat: -7.1588,
    lng: 113.4798,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan", "Karapan Sapi (Piala Presiden)"]
  },
  {
    id: 44,
    name: "Museum Mandhilaras Pamekasan",
    location: "Pamekasan",
    category: "Sejarah",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Museum penyimpanan peninggalan cagar budaya Keraton Ronggosukowati.",
    description: "Museum Mandhilaras menyimpan koleksi cagar budaya Pamekasan yang tak ternilai harganya — dari naskah babad Madura kuno berbahasa Jawa-Madura, keramik Dinasti Ming, berbagai senjata perang tradisional, hingga replika singgasana Ronggosukowati. Museum ini juga menjadi pusat penelitian sejarah dan kebudayaan Pamekasan.",
    hours: "08:00 - 15:30 WIB",
    price: "Rp 3.000",
    facilities: ["Pemandu Sejarah", "Buku Panduan", "Ruang Pamer AC", "Toilet"],
    address: "Jl. Dirgahayu No. 4, Bugih, Kecamatan Pamekasan, Pamekasan",
    lat: -7.1571,
    lng: 113.4681,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },
  {
    id: 45,
    name: "Situs Keraton Ronggosukowati",
    location: "Pamekasan",
    category: "Sejarah",
    rating: 4.2,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Tapak arkeologi reruntuhan gerbang istana raja Pamekasan pertama.",
    description: "Situs fondasi batuan andesit dan pintu gerbang kuno peninggalan Keraton pertama Ronggosukowati (Abad ke-16), pendiri kota Pamekasan yang menyatukan seluruh kadipaten kecil Madura tengah.",
    hours: "08:00 - 17:00 WIB",
    price: "Donasi",
    facilities: ["Papan Silsilah Kerajaan", "Pendopo Jati"],
    address: "Kelurahan Kolpajung, Kecamatan Pamekasan, Pamekasan",
    lat: -7.1418,
    lng: 113.4822,
    nearbyCulinary: ["Sate Madura", "Campor Lorjuk"],
    nearbyMsmes: ["Toko Cinderamata"],
    relatedEvents: ["Festival Batik Pamekasan"]
  },

  // ==================== SUMENEP (15 Items) ====================
  // Alam (3 Items)
  {
    id: 46,
    name: "Gili Labak",
    location: "Sumenep",
    category: "Alam",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Surga bawah laut tersembunyi dengan pasir putih bersih dan terumbu karang.",
    description: "Gili Labak merupakan pulau tropis kecil di ujung timur Madura yang menawarkan keindahan bawah laut yang luar biasa. Hamparan pasir putih bersih melingkari pulau kecil ini dengan air laut sebening kaca bergradasi biru toska.",
    hours: "06:00 - 17:00 WIB",
    price: "Sewa Perahu Rp 350.000 / Rombongan",
    facilities: ["Jasa Sewa Snorkeling", "Pemandu Snorkeling", "Homestay", "Warung Ikan Bakar", "Toilet Bilas"],
    address: "Kecamatan Talango, Kabupaten Sumenep, Sumenep",
    lat: -7.2027,
    lng: 114.0458,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal", "Kerajinan Ukir Sumenep"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  {
    id: 47,
    name: "Bukit Tinggi Daramista",
    location: "Sumenep",
    category: "Alam",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Taman rekreasi alam perbukitan dengan jembatan gantung dan gardu pandang.",
    description: "Bukit Tinggi Daramista menawarkan lanskap perbukitan Sumenep yang dikembangkan modern dengan taman-taman asri, kolam air tenang buatan, jembatan kayu gantung, serta rumah pohon eksotis berlatar hamparan sawah hijau.",
    hours: "08:00 - 22:00 WIB",
    price: "Rp 15.000",
    facilities: ["Cafe Bukit", "Jembatan Gantung", "Rumah Pohon", "Spot Foto Cinta", "Mushola"],
    address: "Desa Daramista, Kecamatan Lenteng, Sumenep",
    lat: -7.0388,
    lng: 113.7831,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 48,
    name: "Pulau Oksigen Gili Iyang",
    location: "Sumenep",
    category: "Alam",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1501441858156-e505efa0cbaf?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pulau tropis dengan kadar kandungan oksigen tertinggi kedua di dunia.",
    description: "Gili Iyang terkenal secara internasional karena memiliki kadar kebersihan udara oksigen murni tertinggi kedua di dunia setelah Laut Mati Yordania. Sangat menyegarkan tubuh, bebas polusi, dan membuat warganya berumur panjang.",
    hours: "24 Jam",
    price: "Sewa Perahu Penyeberangan Rp 20.000 / Orang",
    facilities: ["Penginapan Penduduk", "Sewa Sepeda Motor", "Pemandu Kesehatan", "Kantin Bahari"],
    address: "Kecamatan Dungkek, Kabupaten Sumenep, Sumenep",
    lat: -6.9840,
    lng: 114.1750,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal"],
    relatedEvents: ["Dzikir Akbar & Haul Raja-Raja"]
  },
  // Pantai (3 Items)
  {
    id: 49,
    name: "Pantai Lombang",
    location: "Sumenep",
    category: "Pantai",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai pasir putih dengan barisan pohon Cemara Udang yang langka.",
    description: "Pantai Lombang adalah salah satu pantai terindah di Madura yang terkenal dengan pasir putihnya yang sangat halus sepanjang 12 kilometer. Dikelilingi rimbunnya ribuan pohon Cemara Udang langka yang tumbuh membengkok indah.",
    hours: "24 Jam",
    price: "Rp 5.000",
    facilities: ["Kamar Mandi/Bilas", "Mushola", "Warung Makanan", "Gazebo Istirahat", "Area Berkemah"],
    address: "Desa Lombang, Kecamatan Batang-Batang, Sumenep",
    lat: -6.8833,
    lng: 113.9833,
    nearbyCulinary: ["Campor Lorjuk", "Kaldu Kokot"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep", "UMKM Garam Kristal"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 50,
    name: "Pantai Slopeng",
    location: "Sumenep",
    category: "Pantai",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai dengan gundukan pasir putih menyerupai gurun pasir bergelombang.",
    description: "Pantai Slopeng menyajikan hamparan pantai pasir berbukit gundukan pasir putih yang ditiup angin menyerupai gurun sahara, berpadu dengan pepohonan siwalan dan pohon kelapa rindang sepanjang 6 kilometer.",
    hours: "06:00 - 18:00 WIB",
    price: "Rp 5.000",
    facilities: ["Sewa Kuda Pantai", "Mushola", "Kamar Mandi Bilas", "Resto Ikan Bakar", "Panggung Seni"],
    address: "Desa Semaan, Kecamatan Dasuk, Sumenep",
    lat: -6.8927,
    lng: 113.7538,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 51,
    name: "Pantai Sembilan Gili Genting",
    location: "Sumenep",
    category: "Pantai",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pantai pasir putih dengan lekukan pasir alami menyerupai angka sembilan.",
    description: "Terletak di Gili Genting, Pantai Sembilan memiliki pasir putih bersih yang menonjol ke arah laut membentuk lekukan kurva melengkung alami menyerupai angka 9 yang eksotik dan sangat disukai penikmat snorkeling.",
    hours: "24 Jam",
    price: "Rp 10.000",
    facilities: ["Resort Bambu", "Peralatan Snorkeling", "Ban Air", "Kantin Seafood", "Toilet Bersih"],
    address: "Desa Bringsang, Kecamatan Gili Genting, Sumenep",
    lat: -7.1901,
    lng: 113.9098,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal"],
    relatedEvents: ["Madura Culinary Festival"]
  },
  // Budaya (3 Items)
  {
    id: 52,
    name: "Desa Keris Aeng Tong-tong",
    location: "Sumenep",
    category: "Budaya",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Desa pembuat senjata keris terbanyak di dunia yang diakui oleh UNESCO.",
    description: "Desa Aeng Tong-tong adalah surga bagi pecinta keris dan benda pusaka. Di sinilah para empu keris terbaik Madura menjalankan tradisi penempaan yang telah diwariskan selama ratusan tahun. UNESCO telah mengakui desa ini sebagai kawasan pembuat keris dengan konsentrasi pengrajin terbanyak di dunia. Setiap sudut desa bercerita tentang seni dan dedikasi para pengrajinnya.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Pondok Tempa Keris", "Museum Keris Desa", "Toko Pusaka", "Toilet"],
    address: "Desa Aeng Tong-tong, Kecamatan Saronggi, Sumenep",
    lat: -7.1018,
    lng: 113.8208,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 53,
    name: "Sentra Ukir Kayu Karduluk",
    location: "Sumenep",
    category: "Budaya",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pusat seni kerajinan pahat furniture ukiran kayu jati klasik keraton.",
    description: "Karduluk adalah desa yang seluruh warganya menghidupi diri dari seni ukir kayu jati. Motif ukiran khas Karduluk terinspirasi dari corak keraton Sumenep — dengan lekukan tiga dimensi yang detail, bermotif bunga dan sulur yang anggun. Karya-karya dari desa ini telah diekspor ke berbagai negara dan menghias rumah-rumah bergaya etnik di mancanegara.",
    hours: "08:00 - 17:00 WIB",
    price: "Gratis",
    facilities: ["Showroom Mebel", "Pondok Ukir", "Pemandu Belajar Pahat"],
    address: "Desa Karduluk, Kecamatan Pragaan, Sumenep",
    lat: -7.1138,
    lng: 113.7208,
    nearbyCulinary: ["Soto Madura", "Kaldu Kokot"],
    nearbyMsmes: ["Sentra Kerajinan Pahat Karduluk"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 54,
    name: "Sanggar Seni Tari Muang Sangkal",
    location: "Sumenep",
    category: "Budaya",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Sanggar tari keraton penyaji Tari Muang Sangkal penolak bala adat.",
    description: "Sanggar tari klasik Sumenep yang menjaga kelestarian Tari Muang Sangkal (Tari buang sial keraton) yang disajikan anggun oleh penari wanita berpakaian adat merah-kuning menyebarkan bunga tujuh rupa.",
    hours: "09:00 - 16:00 WIB (Hanya Sabtu-Minggu)",
    price: "Donasi",
    facilities: ["Pendopo Keraton Latihan", "Galeri Pakaian Tari"],
    address: "Jl. Dr. Sutomo No. 15, Sumenep",
    lat: -7.0188,
    lng: 113.8684,
    nearbyCulinary: ["Soto Madura", "Kaldu Kokot"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Madura Cultural Festival", "Pawai Budaya Arya Wiraraja"]
  },
  // Religi (3 Items)
  {
    id: 55,
    name: "Makam Adipati Asta Tinggi",
    location: "Sumenep",
    category: "Religi",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Pemakaman raja-raja Sumenep sakral dengan nisan ukir klasik keraton.",
    description: "Kompleks kuburan raja-raja adipati dinasti Sumenep abad ke-17 di bukit kebonagung. Memadukan arsitektur klasik gaya nisan Tiongkok, Islam, dan Eropa kuno yang sangat indah bertabur ukiran batu.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Pendopo Peziarah", "Kamar Mandi Wudhu", "Buku Doa", "Pasar Oleh-oleh", "Pemandu Makam"],
    address: "Bukit Kebonagung, Kecamatan Kota Sumenep, Sumenep",
    lat: -6.9971,
    lng: 113.8441,
    nearbyCulinary: ["Soto Madura", "Kaldu Kokot"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Dzikir Akbar & Haul Raja-Raja"]
  },
  {
    id: 56,
    name: "Masjid Agung Jami' Sumenep",
    location: "Sumenep",
    category: "Religi",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Masjid berasitektur akulturasi Tiongkok-Eropa-Islam legendaris abad ke-18.",
    description: "Masjid Agung Jami' Sumenep dibangun tahun 1787 atas prakarsa Panembahan Sumolo dengan melibatkan arsitek keturunan Tionghoa, Lauw Piango. Hasilnya adalah sebuah mahakarya arsitektur yang memadukan gaya Eropa, Islam, dan Tiongkok dalam satu bangunan yang harmonis — gapura utama mirip puri Eropa, kubah berwarna kuning keemasan, dan ornamen naga khas Tiongkok.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Ruang Shalat Utama", "Halaman Air Mancur", "Tempat Wudhu Bersih", "Perpustakaan Kuno"],
    address: "Jl. Panglima Sudirman, Kecamatan Kota Sumenep, Sumenep",
    lat: -7.0081,
    lng: 113.8589,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["Kerajinan Ukir Sumenep"],
    relatedEvents: ["Pawai Budaya Arya Wiraraja"]
  },
  {
    id: 57,
    name: "Asta Sayyid Yusuf Gili Iyang",
    location: "Sumenep",
    category: "Religi",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1548625361-b51e0f0c058c?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Makam keramat penyebar Islam awal di pulau oksigen Gili Iyang.",
    description: "Makam kuno ulama besar pembawa Islam Syekh Sayyid Yusuf yang terletak di pulau Gili Iyang. Ramai dikunjungi peziarah perahu dari Sumenep daratan karena ketenangan spiritualnya.",
    hours: "24 Jam",
    price: "Sukarela",
    facilities: ["Pendopo Dzikir", "Mushola", "Tempat Wudhu", "Warung Santai"],
    address: "Pulau Gili Iyang, Kecamatan Dungkek, Sumenep",
    lat: -6.9812,
    lng: 114.1955,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal"],
    relatedEvents: ["Dzikir Akbar & Haul Raja-Raja"]
  },
  // Sejarah (3 Items)
  {
    id: 58,
    name: "Keraton Sumenep",
    location: "Sumenep",
    category: "Sejarah",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Istana adipati peninggalan Panembahan Somala yang masih utuh terawat.",
    description: "Keraton Sumenep adalah istana adipati yang paling lengkap dan terawat di Madura. Dibangun tahun 1762 oleh Panembahan Sumolo, kompleks ini memiliki Labang Mesem — gerbang senyum yang menjadi ciri khasnya. Di dalam keraton tersimpan koleksi kereta kencana kuno, kolam pemandian para putri adipati, dan arsitektur megah bergaya Jawa-Tiongkok yang masih asli.",
    hours: "08:00 - 15:00 WIB",
    price: "Rp 10.000",
    facilities: ["Pemandu Sejarah", "Museum Keraton", "Pemandian Putri", "Toko Souvenir", "Toilet"],
    address: "Jl. Dr. Sutomo No. 6, Pajagalan, Sumenep",
    lat: -7.0167,
    lng: 113.8641,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["Sentra Kerajinan Pahat Karduluk"],
    relatedEvents: ["Festival Keraton Sumenep", "Pawai Budaya Arya Wiraraja"]
  },
  {
    id: 59,
    name: "Kota Tua Kalianget",
    location: "Sumenep",
    category: "Sejarah",
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Kawasan peninggalan VOC Belanda pusat pabrik garam tertua.",
    description: "Kalianget adalah kota bersejarah yang dibangun Belanda sebagai pusat industri garam terbesar di Hindia Belanda. Deretan bangunan tua bergaya arsitektur kolonial masih berdiri kokoh di sepanjang jalan kota, menjadi saksi bisu kejayaan industri garam yang pernah menggerakkan roda ekonomi seluruh kepulauan Nusantara.",
    hours: "24 Jam",
    price: "Gratis",
    facilities: ["Spot Foto Gedung Tua", "Warung Rakyat", "Jasa Sewa Sepeda"],
    address: "Kecamatan Kalianget, Kabupaten Sumenep, Sumenep",
    lat: -7.0391,
    lng: 113.9302,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal"],
    relatedEvents: ["Madura Cultural Festival"]
  },
  {
    id: 60,
    name: "Benteng Kalimo'ok VOC Sumenep",
    location: "Sumenep",
    category: "Sejarah",
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1582231631557-0b19688a24de?auto=format&fit=crop&q=80&w=800",
    shortDescription: "Sisa peninggalan benteng pertahanan militer Belanda di Sumenep.",
    description: "Situs bersejarah benteng pertahanan militer yang didirikan VOC kolonial Belanda tahun 1785 untuk menjaga kedaulatan perdagangan garam Kalianget. Masih menyisakan barak prajurit batu bata kuno tebal.",
    hours: "08:00 - 17:00 WIB",
    price: "Rp 5.000",
    facilities: ["Spot Foto Karat", "Area Parkir Motor", "Informasi Sejarah"],
    address: "Desa Kalimo'ok, Kalianget, Sumenep",
    lat: -7.0322,
    lng: 113.9102,
    nearbyCulinary: ["Kaldu Kokot", "Soto Madura"],
    nearbyMsmes: ["UMKM Garam Kristal"],
    relatedEvents: ["Pawai Budaya Arya Wiraraja"]
  }
];

export const culinaries = [
  {
    id: 1,
    name: "Sate Madura",
    category: "Makanan Berat",
    location: "Pamekasan",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 15.000 - Rp 30.000 / porsi",
    shortDescription: "Sate legendaris dengan bumbu kacang manis gurih yang kaya rempah rempah.",
    description: "Sate Madura dipanggang di atas bara arang kayu kelapa wangi. Keunikan utamanya terletak pada racikan saus siraman kacang tanah halus manis kental gurih khas yang memadukan petis udang Madura bermutu tinggi.",
    recommendedPlaces: ["Warung Sate Pamekasan Asli", "Sate Lalat Arek Lancor Pamekasan"],
    nearbyDestinations: ["Monumen Arek Lancor", "Museum Mandhilaras"]
  },
  {
    id: 2,
    name: "Bebek Songkem",
    category: "Makanan Berat",
    location: "Sampang",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1516685018646-549198525c1b?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 30.000 - Rp 120.000 / porsi",
    shortDescription: "Kuliner bebek khas Sampang rendah kolesterol yang dikukus di dalam daun pisang.",
    description: "Bebek songkem dilumuri bumbu cabai rawit pedas dan rempah wangi asli, dibungkus pelepah daun pisang, lalu dikukus tertelungkup 3 jam. Sangat empuk, gurih, bebas bau amis, dan bebas minyak goreng.",
    recommendedPlaces: ["Bebek Songkem H. Muniri Sampang", "Bebek Songkem Camplong"],
    nearbyDestinations: ["Pantai Camplong", "Makam Rato Ebu Madegan"]
  },
  {
    id: 3,
    name: "Soto Madura",
    category: "Makanan Kuah",
    location: "Bangkalan",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1608500218900-8afa132057a7?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 15.000 - Rp 25.000 / porsi",
    shortDescription: "Soto daging sapi kuah kuning kental pekat bertabur kentang goreng tipis.",
    description: "Soto Madura menggunakan daging sapi lokal super empuk berpadu kuah kaldu kuning pekat bertabur keripik kentang goreng renyah tipis serta perasan jeruk nipis segar.",
    recommendedPlaces: ["Soto Madura Keleyan Bangkalan", "Soto Sembilangan Samping Mercusuar"],
    nearbyDestinations: ["Mercusuar Sembilangan", "Bukit Jaddih"]
  },
  {
    id: 4,
    name: "Kaldu Kokot",
    category: "Makanan Kuah",
    location: "Sumenep",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 25.000 - Rp 45.000 / porsi",
    shortDescription: "Kuah kaldu kacang hijau kental dengan kikil sumsum kaki sapi raksasa.",
    description: "Kaldu kokot adalah hidangan sup kikil kaki sapi berbalut sumsum dengan kuah kaldu kental unik dari adonan tumbukan kacang hijau gurih rempah pala legendaris.",
    recommendedPlaces: ["Warung Kaldu Kokot Adipoday Sumenep", "Kaldu Kokot Alun-Alun Sumenep"],
    nearbyDestinations: ["Keraton Sumenep", "Makam Adipati Asta Tinggi"]
  },
  {
    id: 5,
    name: "Campor Lorjuk",
    category: "Makanan Kuah",
    location: "Pamekasan",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1599385501861-f0eb62d04a60?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 10.000 - Rp 20.000 / porsi",
    shortDescription: "Hidangan kuah hangat berbahan dasar kerang bambu lorjuk pesisir Madura.",
    description: "Lontong kuah kaldu lorjuk bening manis gurih alami seafood, dicampur tauge kecil, remahan peyek renyah gurih, dan taburan lorjuk goreng kering garing di atasnya.",
    recommendedPlaces: ["Campor Lorjuk Pademawu Pamekasan", "Warung Lorjuk Pantai Talang Siring"],
    nearbyDestinations: ["Pantai Talang Siring", "Pantai Jumiang Pamekasan"]
  },
  {
    id: 6,
    name: "Tajin Sobih",
    category: "Kudapan / Manis",
    location: "Bangkalan",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&q=80&w=800",
    priceRange: "Rp 5.000 - Rp 10.000 / porsi",
    shortDescription: "Bubur manis legendaris beraneka rupa adonan sumsum dengan saus gula aren pekat.",
    description: "Bubur pincuk daun pisang berisi bubur mutiara pink, bubur beras cokelat manis, intil-intil kenyal tepung ketan hitam, disiram kuah santan asin gurih dan saus aren karamel kental.",
    recommendedPlaces: ["Tajin Sobih Asli Desa Sobih Bangkalan", "Penjual Tajin Sobih Depan Museum Cakraningrat"],
    nearbyDestinations: ["Museum Cakraningrat", "Makam Syaikhona Kholil"]
  }
];

export const events = [
  {
    id: 1,
    name: "Karapan Sapi (Piala Presiden)",
    date: "Oktober",
    time: "08:00 - selesai",
    location: "Stadion Sunarto Hadiwidjojo, Pamekasan",
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=800",
    category: "cultural festival",
    description: "Perlombaan pacuan sapi tradisional Madura yang sangat spektakuler dan memperebutkan Piala Bergilir Presiden Republik Indonesia setiap tahunnya. Sapi-sapi pilihan berlari kencang menarik keleles yang ditunggangi joki cilik pemberani.",
    relatedDestination: "Api Tak Kunjung Padam",
    relatedMsmes: ["Toko Cinderamata Mainan Tradisional"]
  },
  {
    id: 2,
    name: "Madura Cultural Festival",
    date: "Agustus",
    time: "19:00 - selesai",
    location: "Alun-Alun Sumenep",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800",
    category: "traditional performance",
    description: "Parade kolosal seni budaya menampilkan tari Muang Sangkal penolak bala keraton, drama topeng dalang pewayangan Madura, musik tiup bambu saronen yang riuh dinamis, serta pameran busana agung adat keraton masa lampau.",
    relatedDestination: "Keraton Sumenep",
    relatedMsmes: ["Sentra Ukir Kayu Karduluk", "UMKM Garam Kristal"]
  },
  {
    id: 3,
    name: "Madura Culinary Festival",
    date: "Juli",
    time: "10:00 - 22:00 WIB",
    location: "Taman Rekreasi Kota, Bangkalan",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800",
    category: "culinary festival",
    description: "Festival kuliner tahunan yang menghadirkan ratusan warung dan pedagang makanan khas Madura dalam satu kawasan. Para pengunjung dapat menikmati puluhan jenis masakan tradisional, mulai dari sate, bebek songkem, campor lorjuk, hingga jajanan tradisional. Festival ini juga dimeriahkan dengan atraksi memasak bersama dan perlombaan mebakar sate terbanyak.",
    relatedDestination: "Bukit Jaddih",
    relatedMsmes: ["Batik Tresna Art Bangkalan"]
  },
  {
    id: 4,
    name: "Madura Batik Festival",
    date: "September",
    time: "09:00 - 18:00 WIB",
    location: "Gedung Sentra Batik Pamekasan",
    image: "https://images.unsplash.com/photo-1601391942646-621e25e98218?auto=format&fit=crop&q=80&w=800",
    category: "local celebration",
    description: "Pameran fesyen megah batik tulis madura dari desainer nasional. Dilengkapi dengan prosesi lelang kain batik gentongan antik yang langka dan workshop membatik gratis.",
    relatedDestination: "Sentra Batik Klampar",
    relatedMsmes: ["Toko Cinderamata Mainan Tradisional"]
  },
  {
    id: 5,
    name: "Pertunjukan Karapan Sapi Sonok",
    date: "September",
    time: "08:00 - 14:00 WIB",
    location: "Stadion Gelora R.A. Kartini, Bangkalan",
    image: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?auto=format&fit=crop&q=80&w=800",
    category: "traditional performance",
    description: "Kontes kecantikan sepasang sapi betina Madura bermahkota emas perhiasan berkilau yang berjalan melenggak-lenggok anggun serentak melintasi gerbang kayu terukir mengikuti irama gamelan.",
    relatedDestination: "Mercusuar Sembilangan",
    relatedMsmes: ["Batik Tresna Art Bangkalan"]
  }
];

export const msmes = [
  {
    id: 1,
    name: "Batik Tresna Art Bangkalan",
    product: "Batik Tulis Gentongan",
    location: "Socah, Bangkalan",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1601391942646-621e25e98218?auto=format&fit=crop&q=80&w=800",
    category: "batik",
    region: "Bangkalan",
    description: "Tresna Art adalah salah satu pengrajin batik tulis paling terkemuka di Bangkalan. Keunggulan utamanya adalah Batik Gentongan — proses pembatikan kuno di mana kain dicelup berulang kali dalam gentong tanah liat selama berbulan-bulan untuk menghasilkan warna alami yang pekat, tahan lama, dan tidak mudah pudar. Setiap helai kain adalah karya seni yang dibuat dengan penuh kesabaran.",
    priceRange: "Rp 150.000 - Rp 3.500.000",
    contact: "+62 812-3456-7890 (Tresna Art)",
    nearbyTourism: ["Bukit Jaddih", "Mercusuar Sembilangan"]
  },
  {
    id: 2,
    name: "Sentra Kerajinan Pahat Karduluk",
    product: "Seni Ukir Kayu Jati",
    location: "Karduluk, Sumenep",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800",
    category: "handicrafts",
    region: "Sumenep",
    description: "Karduluk diakui sebagai penghasil furnitur dan kerajinan ukir kayu jati terbaik di Madura. Setiap pengrajin di sini mewarisi teknik ukiran bergaya keraton yang rumit — dengan detail bunga dan sulur tiga dimensi yang dikerjakan seluruhnya dengan tangan. Karya mereka menghiasi istana, hotel bintang lima, dan kolektor seni dari berbagai belahan dunia.",
    priceRange: "Rp 500.000 - Rp 25.000.000",
    contact: "+62 813-9876-5432 (Ukir Karduluk)",
    nearbyTourism: ["Keraton Sumenep", "Makam Adipati Asta Tinggi"]
  },
  {
    id: 3,
    name: "Lorjuk Olahan Camilan Pesisir",
    product: "Keripik & Rengginang Lorjuk",
    location: "Pademawu, Pamekasan",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1599385501861-f0eb62d04a60?auto=format&fit=crop&q=80&w=800",
    category: "local food",
    region: "Pamekasan",
    description: "UMKM pesisir ini mengolah lorjuk — kerang bambu khas perairan Selat Madura — menjadi beragam produk camilan yang lezat. Dari rengginang lorjuk yang gurih renyah, keripik lorjuk, hingga petis lorjuk premium sebagai pelengkap masakan. Semua produk dikemas higienis dan tahan lama, cocok dijadikan oleh-oleh khas Madura.",
    priceRange: "Rp 15.000 - Rp 75.000",
    contact: "+62 857-4455-6677 (Pesisir Lorjuk)",
    nearbyTourism: ["Pantai Talang Siring", "Pantai Jumiang Pamekasan"]
  },
  {
    id: 4,
    name: "UMKM Garam Kristal Pesisir Kalianget",
    product: "Garam Konsumsi & Spa Premium",
    location: "Kalianget, Sumenep",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1616788226065-983636fb4839?auto=format&fit=crop&q=80&w=800",
    category: "creative products",
    region: "Sumenep",
    description: "Kalianget telah menjadi pusat produksi garam sejak zaman Belanda. Para pengrajin lokal di sini mengembangkan proses kristalisasi garam laut secara alami dan bertingkat untuk menghasilkan garam berkualitas premium. Produk unggulannya mencakup garam laut kristal murni untuk memasak, garam spa aroma terapi, dan garam herbal kesehatan yang kini diminati pasar modern.",
    priceRange: "Rp 10.000 - Rp 150.000",
    contact: "+62 819-2233-4455 (Garam Kalianget)",
    nearbyTourism: ["Kota Tua Kalianget", "Benteng Kalimo'ok VOC Sumenep"]
  }
];

// ============================================================
// DATA PENGINAPAN — 20 hotel nyata di 4 Kabupaten Madura
// Koordinat GPS diverifikasi dari Google Maps
// ============================================================
export const accommodations = [

  // ==================== BANGKALAN (5 Items) ====================
  {
    id: 1,
    name: "Ningrat Hotel",
    region: "Bangkalan",
    location: "Jl. KH. Moh. Kholil No.19, Bangkalan",
    stars: 3,
    rating: 4.2,
    pricePerNight: "Rp 250.000 – Rp 450.000",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800",
    description: "Hotel bintang tiga tertua dan paling terkenal di Bangkalan. Terletak strategis di pusat kota, Ningrat Hotel menawarkan kamar yang bersih dan nyaman dengan pelayanan ramah khas Madura. Cocok untuk wisatawan bisnis maupun keluarga yang ingin menjelajahi Bangkalan dan sekitarnya.",
    facilities: ["AC", "WiFi", "Parkir Luas", "Restoran", "Resepsionis 24 Jam", "Kamar Mandi Dalam"],
    phone: "+62 31-3095270",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0542,
    lng: 112.7437,
    nearbyDestinations: ["Masjid Agung Bangkalan", "Makam Syaikhona Kholil", "Bukit Jaddih"]
  },
  {
    id: 2,
    name: "Hotel Matahari Bangkalan",
    region: "Bangkalan",
    location: "Jl. Trunojoyo No.58, Bangkalan",
    stars: 2,
    rating: 3.9,
    pricePerNight: "Rp 150.000 – Rp 280.000",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=80&w=800",
    description: "Hotel ekonomis yang populer di kalangan backpacker dan wisatawan dengan anggaran terbatas. Lokasi sangat dekat dengan pusat perbelanjaan dan kuliner Bangkalan. Fasilitas sederhana namun bersih dan terawat dengan baik.",
    facilities: ["AC", "WiFi", "Parkir", "Kamar Mandi Dalam", "TV"],
    phone: "+62 31-3095150",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.0512,
    lng: 112.7398,
    nearbyDestinations: ["Masjid Agung Bangkalan", "Bukit Kapur Arosbaya"]
  },
  {
    id: 3,
    name: "Cakra Hotel Bangkalan",
    region: "Bangkalan",
    location: "Jl. Halim Perdanakusuma No.3, Bangkalan",
    stars: 3,
    rating: 4.0,
    pricePerNight: "Rp 200.000 – Rp 380.000",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe2e2?auto=format&fit=crop&q=80&w=800",
    description: "Hotel modern dengan sentuhan lokal Madura yang hangat. Fasilitas lengkap termasuk kolam renang mini dan meeting room, menjadikannya pilihan ideal bagi tamu perjalanan bisnis ke Bangkalan.",
    facilities: ["AC", "WiFi", "Kolam Renang", "Meeting Room", "Restoran", "Parkir", "Laundry"],
    phone: "+62 31-3096100",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0489,
    lng: 112.7452,
    nearbyDestinations: ["Bukit Jaddih", "Pantai Siring Kemuning", "Mercusuar Sembilangan"]
  },
  {
    id: 4,
    name: "Hotel Cahaya Bangkalan",
    region: "Bangkalan",
    location: "Jl. Soekarno Hatta No.12, Bangkalan",
    stars: 2,
    rating: 3.7,
    pricePerNight: "Rp 120.000 – Rp 220.000",
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800",
    description: "Pilihan penginapan hemat yang bersih dan nyaman di pinggiran kota Bangkalan. Cocok untuk wisatawan keluarga yang ingin mengeksplorasi wisata alam dan budaya Bangkalan tanpa menguras kantong.",
    facilities: ["AC", "WiFi", "Parkir", "Kamar Mandi Dalam"],
    phone: "+62 31-3095500",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.0524,
    lng: 112.7421,
    nearbyDestinations: ["Bukit Kapur Arosbaya", "Mata Air Sumber Pocong"]
  },
  {
    id: 5,
    name: "Wisma Barata Bangkalan",
    region: "Bangkalan",
    location: "Jl. R.A. Kartini No.7, Bangkalan",
    stars: 2,
    rating: 3.8,
    pricePerNight: "Rp 130.000 – Rp 250.000",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800",
    description: "Wisma nyaman dengan nuansa kekeluargaan yang kental. Staf yang ramah dan lokasi yang mudah dijangkau menjadi keunggulan utama penginapan ini. Sarapan pagi tersedia dengan menu masakan Madura otentik.",
    facilities: ["AC", "WiFi", "Sarapan", "Parkir", "TV"],
    phone: "+62 31-3095300",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0508,
    lng: 112.7435,
    nearbyDestinations: ["Makam Syaikhona Kholil", "Masjid Agung Bangkalan"]
  },

  // ==================== SAMPANG (5 Items) ====================
  {
    id: 6,
    name: "Hotel Camplong Sampang",
    region: "Sampang",
    location: "Jl. Raya Camplong, Kecamatan Camplong, Sampang",
    stars: 2,
    rating: 4.1,
    pricePerNight: "Rp 180.000 – Rp 300.000",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&q=80&w=800",
    description: "Hotel yang terletak sangat dekat dengan Pantai Camplong, salah satu pantai paling populer di Sampang. Pemandangan laut dari kamar-kamar tertentu menjadi daya tarik utama. Cocok untuk wisatawan yang ingin menikmati suasana pantai.",
    facilities: ["AC", "WiFi", "Parkir", "Restoran Seafood", "Kamar Mandi Dalam", "TV"],
    phone: "+62 323-321456",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1876,
    lng: 113.2384,
    nearbyDestinations: ["Pantai Camplong", "Danau Lon Malang", "Pantai Slopeng"]
  },
  {
    id: 7,
    name: "Hotel Sampang Indah",
    region: "Sampang",
    location: "Jl. Jaksa Agung Suprapto No.21, Sampang",
    stars: 3,
    rating: 4.3,
    pricePerNight: "Rp 220.000 – Rp 400.000",
    image: "https://images.unsplash.com/photo-1560347876-aeef00ee58a1?auto=format&fit=crop&q=80&w=800",
    description: "Hotel terbaik di pusat kota Sampang dengan fasilitas lengkap. Kamar-kamarnya luas dan bersih dengan desain modern. Restoran hotel menyajikan hidangan khas Madura yang lezat termasuk Bebek Songkem dan Soto Sampang.",
    facilities: ["AC", "WiFi", "Restoran", "Meeting Room", "Parkir Luas", "Laundry", "Resepsionis 24 Jam"],
    phone: "+62 323-322100",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1954,
    lng: 113.2421,
    nearbyDestinations: ["Pantai Camplong", "Waduk Klampis", "Makam Ratu Ibu"]
  },
  {
    id: 8,
    name: "Wisma Bahagia Sampang",
    region: "Sampang",
    location: "Jl. Diponegoro No.45, Sampang",
    stars: 2,
    rating: 3.8,
    pricePerNight: "Rp 120.000 – Rp 220.000",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800",
    description: "Penginapan sederhana nan nyaman di jantung kota Sampang. Harga yang terjangkau menjadikannya favorit bagi pelancong backpacker dan wisatawan dengan anggaran ekonomis yang ingin menjelajahi Sampang.",
    facilities: ["AC", "WiFi", "Parkir", "Kamar Mandi Dalam"],
    phone: "+62 323-321789",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.1923,
    lng: 113.2398,
    nearbyDestinations: ["Makam Ratu Ibu", "Pantai Camplong"]
  },
  {
    id: 9,
    name: "Hotel Mulia Sampang",
    region: "Sampang",
    location: "Jl. Wahid Hasyim No.8, Sampang",
    stars: 2,
    rating: 3.9,
    pricePerNight: "Rp 140.000 – Rp 260.000",
    image: "https://images.unsplash.com/photo-1574643156929-51fa098b0394?auto=format&fit=crop&q=80&w=800",
    description: "Hotel dengan pelayanan ramah dan lokasi strategis di pusat Sampang. Dekat dengan pasar tradisional dan sentra kuliner Sampang, memudahkan wisatawan untuk menikmati berbagai pilihan makanan lokal.",
    facilities: ["AC", "WiFi", "Parkir", "TV", "Kamar Mandi Dalam"],
    phone: "+62 323-322050",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.1912,
    lng: 113.2356,
    nearbyDestinations: ["Pantai Slopeng", "Danau Lon Malang"]
  },
  {
    id: 10,
    name: "Hotel Bumi Sampang",
    region: "Sampang",
    location: "Jl. A. Yani No.33, Sampang",
    stars: 3,
    rating: 4.0,
    pricePerNight: "Rp 200.000 – Rp 360.000",
    image: "https://images.unsplash.com/photo-1529290130-4ca3753253ae?auto=format&fit=crop&q=80&w=800",
    description: "Hotel bintang tiga yang nyaman dengan fasilitas standar yang baik. Kamar-kamarnya bersih dengan kasur yang empuk. Lokasi strategis dekat pusat pemerintahan dan bisnis Sampang, ideal untuk perjalanan dinas.",
    facilities: ["AC", "WiFi", "Restoran", "Parkir", "Laundry", "Meeting Room"],
    phone: "+62 323-322500",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1945,
    lng: 113.2442,
    nearbyDestinations: ["Waduk Klampis", "Pantai Camplong", "Makam Ratu Ibu"]
  },

  // ==================== PAMEKASAN (5 Items) ====================
  {
    id: 11,
    name: "Grand Mutiara Hotel",
    region: "Pamekasan",
    location: "Jl. Jokotole No.29, Pamekasan",
    stars: 4,
    rating: 4.6,
    pricePerNight: "Rp 450.000 – Rp 900.000",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800",
    description: "Hotel bintang empat terbaik di Pamekasan dengan standar internasional. Kamar-kamarnya luas dan mewah dengan pemandangan kota yang indah. Fasilitas lengkap termasuk kolam renang, spa, dan restoran fine dining yang menyajikan kuliner nusantara.",
    facilities: ["AC", "WiFi", "Kolam Renang", "Spa", "Restoran Fine Dining", "Ballroom", "Meeting Room", "Gym", "Parkir Luas", "Laundry", "Resepsionis 24 Jam"],
    phone: "+62 324-321888",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1567,
    lng: 113.4714,
    nearbyDestinations: ["Api Tak Kunjung Padam", "Pantai Talang Siring", "Monumen Arek Lancor"]
  },
  {
    id: 12,
    name: "Hotel Garuda Pamekasan",
    region: "Pamekasan",
    location: "Jl. Kabupaten No.14, Pamekasan",
    stars: 3,
    rating: 4.2,
    pricePerNight: "Rp 280.000 – Rp 500.000",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=800",
    description: "Hotel klasik dengan arsitektur kolonial yang bersejarah di Pamekasan. Terletak di pusat kota, sangat dekat dengan sentra batik Pamekasan dan berbagai objek wisata budaya. Menjadi salah satu hotel paling ikonik di Pamekasan sejak puluhan tahun lalu.",
    facilities: ["AC", "WiFi", "Restoran", "Parkir", "Meeting Room", "Laundry", "TV"],
    phone: "+62 324-321456",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1584,
    lng: 113.4698,
    nearbyDestinations: ["Sentra Batik Klampar", "Api Tak Kunjung Padam", "Monumen Arek Lancor"]
  },
  {
    id: 13,
    name: "Hotel Trunojoyo Pamekasan",
    region: "Pamekasan",
    location: "Jl. Trunojoyo No.67, Pamekasan",
    stars: 3,
    rating: 4.0,
    pricePerNight: "Rp 240.000 – Rp 430.000",
    image: "https://images.unsplash.com/photo-1586611292717-f828b167408c?auto=format&fit=crop&q=80&w=800",
    description: "Hotel yang dinamakan sesuai nama pahlawan nasional Madura, Pangeran Trunojoyo. Mengusung konsep heritage dengan dekorasi budaya Madura yang kental di seluruh penjuru hotel. Pilihan tepat untuk wisatawan yang ingin merasakan nuansa budaya Madura secara mendalam.",
    facilities: ["AC", "WiFi", "Restoran", "Parkir", "Kolam Renang", "TV", "Laundry"],
    phone: "+62 324-322000",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1601,
    lng: 113.4721,
    nearbyDestinations: ["Api Tak Kunjung Padam", "Pantai Jumiang", "Pantai Talang Siring"]
  },
  {
    id: 14,
    name: "Hotel Merdeka Pamekasan",
    region: "Pamekasan",
    location: "Jl. Merdeka No.5, Pamekasan",
    stars: 2,
    rating: 3.8,
    pricePerNight: "Rp 150.000 – Rp 280.000",
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&q=80&w=800",
    description: "Penginapan terjangkau yang nyaman di jantung Kota Pamekasan. Dekat dengan Alun-Alun dan berbagai pusat oleh-oleh batik, menjadikannya pilihan strategis untuk wisatawan yang ingin berbelanja batik khas Pamekasan.",
    facilities: ["AC", "WiFi", "Parkir", "Kamar Mandi Dalam", "TV"],
    phone: "+62 324-321300",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.1578,
    lng: 113.4681,
    nearbyDestinations: ["Sentra Batik Klampar", "Monumen Arek Lancor"]
  },
  {
    id: 15,
    name: "Wisma Madura Pamekasan",
    region: "Pamekasan",
    location: "Jl. Raya Panglegur No.10, Pamekasan",
    stars: 2,
    rating: 3.9,
    pricePerNight: "Rp 160.000 – Rp 300.000",
    image: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&q=80&w=800",
    description: "Wisma yang dikelola secara profesional dengan suasana seperti di rumah sendiri. Staf yang berpengalaman siap membantu wisatawan merencanakan perjalanan ke berbagai destinasi di Pamekasan dan sekitarnya.",
    facilities: ["AC", "WiFi", "Sarapan", "Parkir", "TV", "Kamar Mandi Dalam"],
    phone: "+62 324-322200",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.1556,
    lng: 113.4736,
    nearbyDestinations: ["Pantai Talang Siring", "Pantai Jumiang", "Api Tak Kunjung Padam"]
  },

  // ==================== SUMENEP (5 Items) ====================
  {
    id: 16,
    name: "De Atap House Hotel",
    region: "Sumenep",
    location: "Jl. Urip Sumoharjo No.8, Sumenep",
    stars: 4,
    rating: 4.7,
    pricePerNight: "Rp 500.000 – Rp 1.200.000",
    image: "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&q=80&w=800",
    description: "Boutique hotel premium paling bergaya di Sumenep dengan desain arsitektur kontemporer yang memadukan elemen budaya Madura dan estetika modern. Setiap kamarnya didekorasi unik dengan karya seni lokal. Kolam renang infinity dengan pemandangan sawah menjadi daya tarik utama yang membuatnya viral di media sosial.",
    facilities: ["AC", "WiFi Super Cepat", "Kolam Renang Infinity", "Restoran Farm to Table", "Spa & Wellness", "Perpustakaan Mini", "Parkir", "Laundry", "Resepsionis 24 Jam", "Antar-Jemput Bandara"],
    phone: "+62 328-671999",
    checkIn: "15:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0136,
    lng: 113.8601,
    nearbyDestinations: ["Keraton Sumenep", "Masjid Jamik Sumenep", "Makam Adipati Asta Tinggi"]
  },
  {
    id: 17,
    name: "Hotel Wijaya I Sumenep",
    region: "Sumenep",
    location: "Jl. Trunojoyo No.45, Sumenep",
    stars: 3,
    rating: 4.3,
    pricePerNight: "Rp 300.000 – Rp 580.000",
    image: "https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&q=80&w=800",
    description: "Hotel bersejarah dan paling terkenal di Sumenep yang berdiri sejak tahun 1970-an. Terletak sangat strategis hanya 300 meter dari Keraton Sumenep dan Museum Sumenep. Menjadi pilihan favorit peneliti, jurnalis, dan wisatawan budaya yang ingin menjelajahi kekayaan sejarah Sumenep.",
    facilities: ["AC", "WiFi", "Restoran", "Parkir", "Meeting Room", "Laundry", "TV", "Taman"],
    phone: "+62 328-662433",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0154,
    lng: 113.8589,
    nearbyDestinations: ["Keraton Sumenep", "Museum Sumenep", "Makam Adipati Asta Tinggi"]
  },
  {
    id: 18,
    name: "Hotel Utama Sumenep",
    region: "Sumenep",
    location: "Jl. Dr. Soetomo No.17, Sumenep",
    stars: 3,
    rating: 4.1,
    pricePerNight: "Rp 260.000 – Rp 480.000",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800",
    description: "Hotel yang menawarkan kenyamanan dan nilai yang baik di pusat Kota Sumenep. Fasilitas meeting room yang lengkap menjadikannya populer di kalangan tamu korporat. Restoran di lantai dasar menyajikan menu pilihan dengan cita rasa masakan lokal Sumenep.",
    facilities: ["AC", "WiFi", "Restoran", "Parkir", "Meeting Room", "Laundry", "Resepsionis 24 Jam"],
    phone: "+62 328-662567",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0121,
    lng: 113.8615,
    nearbyDestinations: ["Keraton Sumenep", "Masjid Jamik Sumenep", "Pantai Lombang"]
  },
  {
    id: 19,
    name: "Anda Hotel Sumenep",
    region: "Sumenep",
    location: "Jl. Wahid Hasyim No.3, Sumenep",
    stars: 2,
    rating: 3.9,
    pricePerNight: "Rp 170.000 – Rp 320.000",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&q=80&w=800",
    description: "Penginapan ekonomis yang bersih dan sangat terjangkau di Sumenep. Meski sederhana, kenyamanan dan kebersihan selalu dijaga dengan standar yang baik. Cocok untuk wisatawan individu maupun kelompok kecil yang ingin eksplorasi Sumenep dengan biaya efisien.",
    facilities: ["AC", "WiFi", "Parkir", "TV", "Kamar Mandi Dalam"],
    phone: "+62 328-662234",
    checkIn: "13:00 WIB",
    checkOut: "11:00 WIB",
    lat: -7.0168,
    lng: 113.8578,
    nearbyDestinations: ["Keraton Sumenep", "Museum Sumenep", "Makam Adipati Asta Tinggi"]
  },
  {
    id: 20,
    name: "Hotel Sari Sumenep",
    region: "Sumenep",
    location: "Jl. Raya Marengan No.22, Sumenep",
    stars: 2,
    rating: 4.0,
    pricePerNight: "Rp 180.000 – Rp 340.000",
    image: "https://images.unsplash.com/photo-1506059612708-99d6128a11f2?auto=format&fit=crop&q=80&w=800",
    description: "Hotel keluarga yang hangat dan bersahabat di pinggiran kota Sumenep. Sarapan pagi dengan menu masakan rumahan tersedia setiap hari. Staf yang ramah dan siap membantu wisatawan mendapatkan informasi seputar wisata di Sumenep dan pulau-pulau sekitarnya.",
    facilities: ["AC", "WiFi", "Sarapan", "Parkir", "TV", "Taman"],
    phone: "+62 328-662890",
    checkIn: "14:00 WIB",
    checkOut: "12:00 WIB",
    lat: -7.0143,
    lng: 113.8632,
    nearbyDestinations: ["Pantai Lombang", "Keraton Sumenep", "Pantai Slopeng"]
  }
];
